language: erlang
otp_release:
  - 17.0
notifications:
  email: 
    - maxim@synrc.com
    - doxtop@synrc.com
  irc: "chat.freenode.net#n2o"
script: "(cd samples; ./mad dep com pla)"
install: "samples/mad"
